<a href="https://colab.research.google.com/github/leventdusunceli/Basic_ML_Models/blob/main/car_safety_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

from google.colab import drive
drive.mount('/content/drive')
import os 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Mounted at /content/drive

In [3]:
os.chdir("/content/drive/MyDrive/Online_Lecture_Notes/Machine_Learning_AZ/Practice_Folder/Car_safety_evaluation")
dataset= pd.read_csv("car_evaluation.csv", header = None)
dataset.head(5)

       0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [4]:
dataset.columns = ["Price","Maintenance", "Doors","People","Boot_Size","Safety_Rating","Acceptability"]

In [13]:
from sklearn import preprocessing 
from sklearn.model_selection import train_test_split

le = preprocessing.LabelEncoder()

X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

X[:,0] = le.fit_transform(X[:,0])
X[:,1] = le.fit_transform(X[:,1])
X[:,2] = le.fit_transform(X[:,2])
X[:,3] = le.fit_transform(X[:,3])
X[:,4] = le.fit_transform(X[:,4])
X[:,5] = le.fit_transform(X[:,5])
y = le.fit_transform(y)


x_train,x_test,y_train,y_test = train_test_split(X,y,test_size= 0.1)

In [15]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 6)
classifier.fit(x_train,y_train)

score = classifier.score(x_test,y_test)*100
print("Accuracy: %3.f" %score, "%" )

Accuracy:  90 %

In [21]:
y_pred = classifier.predict(x_test)

y_actu = pd.Series(le.inverse_transform(y_test),name= "Actual")
y_predict = pd.Series (le.inverse_transform(y_pred), name="Predicted")
df_conf = pd.crosstab(y_actu,y_predict) 
df_conf

Predicted  acc  good  unacc  vgood
Actual
acc         31     0      7      0
good         6     3      1      0
unacc        1     0    119      0
vgood        2     0      0      3